# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "litemall-all"

[default.build.parameters]
cached = true
parallel = true
# 使用容器环境构建项目
#use_container = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = false
# 使用具体的S3桶
#s3_bucket = 'your-s3-bucket'
# 使用具体的S3桶内路径
#s3_prefix = '<your-s3-prefix>'


[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
