AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  litemall

  litemall backend

Globals:
  Function:
    Timeout: 60

Resources:
  PetstoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      VpcConfig:
        SecurityGroupIds:
          - sg-0f535b902427074e7
        SubnetIds:
          - subnet-04fcf4683c6a14b4d
          - subnet-03f68e34e9d2f87f0
          - subnet-081ba9c36f1afbc3d
      MemorySize: 8192
      Handler: run.sh
      CodeUri: litemall-all/
      Runtime: java17
      # 函数名称
      FunctionName: litemall-all
      AutoPublishAlias: live
      SnapStart:
        ApplyOn: PublishedVersions
      Environment:
        Variables:
          RUST_LOG: info
          READINESS_CHECK_PATH: /admin/index/index
          #          REMOVE_BASE_PATH: /v1
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          # 开启如下JVM启动参数：使用分层编译，使用
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=4 -XX:+UseParallelGC
      Layers:
        - !Sub arn:aws:lambda:us-east-1:753240598075:layer:LambdaAdapterLayerX86:20
      Events:
        Root:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
        Petstore:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  PetstoreApi:
    Description: "API Gateway endpoint URL for Prod stage for Petstore function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/admin/index/index"

