AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  litemall

  litemall backend

Globals:
  Function:
    Timeout: 60

Resources:
  # 创建api-gateway资源：https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html
  FunctionApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: aws lambda's api gateway
      Name: lambda-gateway
      CorsConfiguration:
        AllowOrigins:
          - "https://*"
          - "http://*"
        AllowHeaders:
          - "Content-Type"
          - "X-Litemall-Admin-Token"
        AllowMethods:
          - "*"
        AllowCredentials: true
  litemallFunction:
    Type: AWS::Serverless::Function
    Properties:
      VpcConfig:
        SecurityGroupIds:
          - <your-security-group-ids>
        SubnetIds:
          - <your-subnet-ids-1>
          - <your-subnet-ids-2>
      MemorySize: 8192
      Handler: run.sh
      CodeUri: litemall-all/
      Runtime: java17
      # 函数名称
      FunctionName: litemall-all
      Role: "arn:aws:iam::<your-aws-account-id>:role/lambdaFunctionRole"
      AutoPublishAlias: live
      SnapStart:
        ApplyOn: PublishedVersions
      Environment:
        Variables:
          RUST_LOG: info
          READINESS_CHECK_PATH: /admin/index/index
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          # 开启如下JVM启动参数：使用分层编译，使用
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=4 -XX:+UseParallelGC
      Layers:
        - !Sub arn:aws:lambda:us-east-1:753240598075:layer:LambdaAdapterLayerX86:21
      Events:
        litemallApi:
          Type: HttpApi
          Properties:
            # 引用api-gateway资源的id
            ApiId:
              Ref: FunctionApiGateway
            Path: /{proxy+}
            Method: ANY
Outputs:
  AdminWebHomepage:
    Description: "Admin endpoint Homepage URL"
    Value: !Sub "https://${FunctionApiGateway}.execute-api.${AWS::Region}.${AWS::URLSuffix}/index.html"
  AdminApiURL:
    Description: "Admin endpoint API URL"
    Value: !Sub "https://${FunctionApiGateway}.execute-api.${AWS::Region}.${AWS::URLSuffix}/admin/index/index"

