package org.linlinjava.litemall.db.domain;

import java.time.LocalDate;

public class LitemallUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_user.id
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_user.username
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_user.password
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_user.gender
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_user.birthday
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    private LocalDate birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_user.register_time
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    private LocalDate registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_user.last_login_time
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    private LocalDate lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_user.last_login_ip
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    private String lastLoginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_user.user_level
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    private String userLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_user.nickname
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_user.mobile
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_user.register_ip
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    private String registerIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_user.avatar
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_user.weixin_openid
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    private String weixinOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_user.status
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_user.id
     *
     * @return the value of litemall_user.id
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_user.id
     *
     * @param id the value for litemall_user.id
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_user.username
     *
     * @return the value of litemall_user.username
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_user.username
     *
     * @param username the value for litemall_user.username
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_user.password
     *
     * @return the value of litemall_user.password
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_user.password
     *
     * @param password the value for litemall_user.password
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_user.gender
     *
     * @return the value of litemall_user.gender
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_user.gender
     *
     * @param gender the value for litemall_user.gender
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_user.birthday
     *
     * @return the value of litemall_user.birthday
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public LocalDate getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_user.birthday
     *
     * @param birthday the value for litemall_user.birthday
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public void setBirthday(LocalDate birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_user.register_time
     *
     * @return the value of litemall_user.register_time
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public LocalDate getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_user.register_time
     *
     * @param registerTime the value for litemall_user.register_time
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public void setRegisterTime(LocalDate registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_user.last_login_time
     *
     * @return the value of litemall_user.last_login_time
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public LocalDate getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_user.last_login_time
     *
     * @param lastLoginTime the value for litemall_user.last_login_time
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public void setLastLoginTime(LocalDate lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_user.last_login_ip
     *
     * @return the value of litemall_user.last_login_ip
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_user.last_login_ip
     *
     * @param lastLoginIp the value for litemall_user.last_login_ip
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_user.user_level
     *
     * @return the value of litemall_user.user_level
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public String getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_user.user_level
     *
     * @param userLevel the value for litemall_user.user_level
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public void setUserLevel(String userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_user.nickname
     *
     * @return the value of litemall_user.nickname
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_user.nickname
     *
     * @param nickname the value for litemall_user.nickname
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_user.mobile
     *
     * @return the value of litemall_user.mobile
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_user.mobile
     *
     * @param mobile the value for litemall_user.mobile
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_user.register_ip
     *
     * @return the value of litemall_user.register_ip
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public String getRegisterIp() {
        return registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_user.register_ip
     *
     * @param registerIp the value for litemall_user.register_ip
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_user.avatar
     *
     * @return the value of litemall_user.avatar
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_user.avatar
     *
     * @param avatar the value for litemall_user.avatar
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_user.weixin_openid
     *
     * @return the value of litemall_user.weixin_openid
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public String getWeixinOpenid() {
        return weixinOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_user.weixin_openid
     *
     * @param weixinOpenid the value for litemall_user.weixin_openid
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public void setWeixinOpenid(String weixinOpenid) {
        this.weixinOpenid = weixinOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_user.status
     *
     * @return the value of litemall_user.status
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_user.status
     *
     * @param status the value for litemall_user.status
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", gender=").append(gender);
        sb.append(", birthday=").append(birthday);
        sb.append(", registerTime=").append(registerTime);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", lastLoginIp=").append(lastLoginIp);
        sb.append(", userLevel=").append(userLevel);
        sb.append(", nickname=").append(nickname);
        sb.append(", mobile=").append(mobile);
        sb.append(", registerIp=").append(registerIp);
        sb.append(", avatar=").append(avatar);
        sb.append(", weixinOpenid=").append(weixinOpenid);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallUser other = (LitemallUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getGender() == null ? other.getGender() == null : this.getGender().equals(other.getGender()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getRegisterTime() == null ? other.getRegisterTime() == null : this.getRegisterTime().equals(other.getRegisterTime()))
            && (this.getLastLoginTime() == null ? other.getLastLoginTime() == null : this.getLastLoginTime().equals(other.getLastLoginTime()))
            && (this.getLastLoginIp() == null ? other.getLastLoginIp() == null : this.getLastLoginIp().equals(other.getLastLoginIp()))
            && (this.getUserLevel() == null ? other.getUserLevel() == null : this.getUserLevel().equals(other.getUserLevel()))
            && (this.getNickname() == null ? other.getNickname() == null : this.getNickname().equals(other.getNickname()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getRegisterIp() == null ? other.getRegisterIp() == null : this.getRegisterIp().equals(other.getRegisterIp()))
            && (this.getAvatar() == null ? other.getAvatar() == null : this.getAvatar().equals(other.getAvatar()))
            && (this.getWeixinOpenid() == null ? other.getWeixinOpenid() == null : this.getWeixinOpenid().equals(other.getWeixinOpenid()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated Tue Mar 20 00:11:33 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getGender() == null) ? 0 : getGender().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getRegisterTime() == null) ? 0 : getRegisterTime().hashCode());
        result = prime * result + ((getLastLoginTime() == null) ? 0 : getLastLoginTime().hashCode());
        result = prime * result + ((getLastLoginIp() == null) ? 0 : getLastLoginIp().hashCode());
        result = prime * result + ((getUserLevel() == null) ? 0 : getUserLevel().hashCode());
        result = prime * result + ((getNickname() == null) ? 0 : getNickname().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getRegisterIp() == null) ? 0 : getRegisterIp().hashCode());
        result = prime * result + ((getAvatar() == null) ? 0 : getAvatar().hashCode());
        result = prime * result + ((getWeixinOpenid() == null) ? 0 : getWeixinOpenid().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        username("username"),
        password("password"),
        gender("gender"),
        birthday("birthday"),
        registerTime("register_time"),
        lastLoginTime("last_login_time"),
        lastLoginIp("last_login_ip"),
        userLevel("user_level"),
        nickname("nickname"),
        mobile("mobile"),
        registerIp("register_ip"),
        avatar("avatar"),
        weixinOpenid("weixin_openid"),
        status("status");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}