spring:
  profiles:
    active: db, core, admin, wx
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  config: classpath:logback-spring.xml